name: Deploy DreamHome (Script Version)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
      
      - name: Build and push docker image 
        run: |
          docker build -t ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/dreamhome:latest .
          docker push ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/dreamhome:latest

      - name: Deploy using deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Clone/update repository
            if [ ! -d "/opt/dreamhome" ]; then
              sudo mkdir -p /opt/dreamhome
              sudo chown $USER:$USER /opt/dreamhome
              cd /opt && git clone https://github.com/${{ github.repository }}.git dreamhome
            else
              cd /opt/dreamhome && git pull origin main
            fi
            
            # Login to ACR
            docker login ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io -u ${{ secrets.AZURE_REGISTRY_USERNAME }} -p ${{ secrets.AZURE_REGISTRY_PASSWORD }}
            
            # Make deploy script executable and run
            chmod +x /opt/dreamhome/scripts/deploy.sh
            /opt/dreamhome/scripts/deploy.sh "${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/dreamhome:latest" "${{ secrets.DATABASE_URL }}" "${{ secrets.EMAIL_USER }}" "${{ secrets.EMAIL_PASS }}" "${{ secrets.GOOGLE_CLIENT_ID }}" "${{ secrets.GOOGLE_CLIENT_SECRET }}" "${{ secrets.NEXTAUTH_URL }}" "${{ secrets.NEXTAUTH_SECRET }}"